//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.BuildLists = new HashSet<BuildList>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> ProductBasePrice { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Description { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<BuildList> BuildLists { get; set; }
    }
}
